### ISSUE TITLE
Update to DeepSpeech 0.9.3 ?

### ISSUE THREAD

**Issue by no-identd** [T-vK/Termux-DeepSpeech#1]
🥺
👉👈

**Comment by T-vK** [comment]
Okay, I'll try. Does this work for you? https://github.com/T-vK/Termux-DeepSpeech/tree/feat/add-0.9.3-support

**Comment by T-vK** [comment]
I updated the code, merged it into the master and tested it on Android. It works fine, have fun with it: https://github.com/T-vK/Termux-DeepSpeech

Feel free to re-open if you have any issues.

**Comment by no-identd** [comment]
I have yet to test it, because Termux pulled some openssl trollery on me and I refuse to let it troll me, so I have to investigate & unbreak that first, but I already greatly appreciate this, thank you, I'll let you know how it works out for me!!

**Comment by T-vK** [comment]
Not sure if this is relevant, but I had a weird `CANNOT LINK EXECUTABLE` `libssl not found` issue earlier today every time I ran commands like `git`. I managed to fix it by removing the git package, running `pkg update` and then installing the package again.
